-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
-- !!! Сгенерировано в программе pgAdmin.
-- 1) Создаём таблицы этим скриптом
-- 2) Запускаем скрипт person.sql
-- 3) Запускаем скрипт room.sql
-- 4) Запускаем скрипт room_participants.sql
-- 5) Запускаем скрипт message.sql
-- Именно в таком порядке
-- Пароль в person такой же, как и логин. Если логин "а", то и пароль "a"
BEGIN;


CREATE TABLE IF NOT EXISTS public.message
(
    id bigint NOT NULL DEFAULT nextval('message_id_seq'::regclass),
    content character varying(255) COLLATE pg_catalog."default",
    room_id integer NOT NULL,
    "timestamp" timestamp without time zone,
    sender_id integer,
    CONSTRAINT message_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.person
(
    id integer NOT NULL DEFAULT nextval('person_id_seq'::regclass),
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id integer NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.room
(
    id integer NOT NULL DEFAULT nextval('room_id_seq'::regclass),
    creator_id integer NOT NULL,
    theme_of_room character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT room_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.room_participants
(
    room_id integer NOT NULL,
    participants_id integer NOT NULL
);

ALTER TABLE IF EXISTS public.message
    ADD CONSTRAINT fk6p9dy39ram5rqdl84nciff92j FOREIGN KEY (sender_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.room_participants
    ADD CONSTRAINT fk440oswk1emp4o62bwynomg4r8 FOREIGN KEY (participants_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.room_participants
    ADD CONSTRAINT fkd93x26glimf3l3f05ukaoi6ry FOREIGN KEY (room_id)
        REFERENCES public.room (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;